import {
    AtomIcon,
    BracketsCurlyIcon,
    BrowsersIcon,
    ChatCircleIcon,
    CodeIcon,
    DatabaseIcon,
    FileTextIcon,
    GithubLogoIcon,
    GraduationCapIcon,
    Icon,
    LayoutIcon,
    MonitorIcon,
    NotebookIcon,
    PaintBrushIcon,
    PenNibIcon,
    RocketIcon,
    SparkleIcon,
    StackIcon,
    StarIcon,
    TrophyIcon,
    VideoIcon,
    WrenchIcon,
} from '@phosphor-icons/react';
import { IndicationIconName } from '@/data';

export const iconMap: Record<IndicationIconName, Icon> = {
    Monitor: MonitorIcon,
    PenNib: PenNibIcon,
    GithubLogo: GithubLogoIcon,
    Wrench: WrenchIcon,
    Code: CodeIcon,
    PaintBrush: PaintBrushIcon,
    ChatCircle: ChatCircleIcon,
    Notebook: NotebookIcon,
    Video: VideoIcon,
    FileText: FileTextIcon,
    Database: DatabaseIcon,
    Rocket: RocketIcon,
    Atom: AtomIcon,
    BracketsCurly: BracketsCurlyIcon,
    Layout: LayoutIcon,
    Sparkle: SparkleIcon,
    Stack: StackIcon,
    GraduationCap: GraduationCapIcon,
    Trophy: TrophyIcon,
    Browsers: BrowsersIcon,
};
